package.json, src/components/AppBarSearch/index.js, src/components/AppBarSearch/styles.js, src/components/FiltersToggleBtn/index.js, src/components/Sets/SetList/index.js, src/containers/SetsContainer/index.js, src/lib/translations/en.js, src/lib/translations/fr.js, yarn.lock
- Search on current local items
- Focus input on mount
=> feat:  Add search ui

src/components/EmptySection/index.js, src/components/Sets/SetList/index.js, src/containers/SetsContainer/index.js, src/lib/translations/en.js, src/lib/translations/fr.js
=> feat:  Add empty section component

src/components/FiltersToggleBtn/index.js, src/components/Sets/Set/Tabs.js, src/components/Sets/SetList/index.js, src/components/Sets/SetListItem/index.js, src/components/Sets/SetListItem/styles.js, src/components/Shared/TopBar.js, src/components/SideSheet/styles.js, src/constants/ui.js, src/containers/SetChildrenContainer/index.js, src/containers/SetContainer/index.js, src/containers/SetCurrentLevelContainer/index.js, src/containers/SetFormulasContainer/index.js, src/containers/SetsContainer/index.js, src/containers/SetsContainer/styles.js, src/lib/setHelpers.js, src/lib/translations/en.js, src/lib/translations/fr.js
=> feat: Add set show

.eslintrc, README.md, package.json, src/components/Shared/TopBar.js, src/components/Simulations/SimulationList.js, src/containers/SimulationContainer/index.js, src/containers/SimulationsContainer/index.js, src/containers/SimulationsContainer/styles.js
This adds back the git commit hook to run `prettifier-eslint`, if you don't want to commit hook set `HUSKY_SKIP_HOOKS=1` as an env flag (but you'll need to run `yarn format` yourself!)
(This also fixes a few files that were not formatted corrected)
=> Add yarn format command

src/components/AppBarSearch/index.js, src/components/AppBarSearch/styles.js, src/containers/SetsContainer/index.js
=> feat: Add search clear btn

src/App.js, src/components/Drawers/DrawerItem.js, src/components/SetsGroups/SetsGroupsList/index.js, src/components/SetsGroups/SetsGroupsListItem/index.js, src/components/SetsGroups/SetsGroupsListItem/styles.js, src/components/SetsGroups/index.js, src/components/SetsGroups/styles.js, src/containers/SetsGroupsContainer/index.js
=> feat: Add sets groups items list

src/components/Shared/MultiSelectDropdown.js, src/components/Simulation/Filters.js, src/components/Simulation/index.js, src/components/Simulation/list.js, src/components/Simulation/parts.js, src/lib/formUItils.test.js, src/lib/formUtils.js, src/lib/translations/en.js, src/lib/translations/fr.js
This allows a user to select which parts of the simulation he wants to see.
=> feat: Add selecting/filtering for simulation

src/App.js, src/components/Simulation/SimulationPart.js, src/components/Simulation/Table/table.js, src/components/Simulation/index.js, src/containers/SimulationContainer/index.js, src/containers/SimulationsContainer/index.js
For now name is undefined because it’s not in the mock server api simulation payload
- Moved to standard route params 
- Rename some variable
- Destructure simulation payload on simulation component
- Make Simulation more resilient to async api loading
=> refactor: Simulation routing

src/components/Simulation/index.js
Based on #18 so needs rebase after 18 is merged
=> feat: Add bottom sheet

src/components/Simulation/ExpandableCellContent/index.js, src/components/Simulation/ExpandableCellContent/styles.js, src/components/Simulation/SimulationBlock/PeriodView/index.js, src/components/Simulation/SimulationBlock/Table/index.js, src/components/Simulation/SimulationBlock/Table/styles.js, src/components/Simulation/SimulationBlock/index.js, src/components/Simulation/SimulationBlocks.js, src/components/Simulation/index.js, src/containers/SimulationContainer/index.js, src/lib/translations/en.js, src/lib/translations/fr.js
=> Add cell explanation cell content base

mock-server/README.md, mock-server/app.rb, mock-server/data/project.json
This endpoint will get more data into it relationships, but the data
layout will remain as it its, there might  be other attributes, but I
think these are the main ones we want to see.
=> Add /api/project for current project information

src/actions/api.js, src/components/Simulation/ExpandableCellContent/ViewOnDhis2Btn/index.js, src/components/Simulation/ExpandableCellContent/index.js, src/components/Simulation/Header.js, src/components/Simulation/SimulationBlock/PeriodView/index.js, src/components/Simulation/SimulationBlock/Table/Solution.js, src/components/Simulation/SimulationBlock/Table/index.js, src/components/Simulation/SimulationBlock/Table/styles.js, src/components/Simulation/SimulationBlock/index.js, src/lib/translations/en.js, src/lib/translations/fr.js
=> feat: Make a better cell explanation panel

src/actions/ui.js, src/components/Simulation/SimulationBlock/Table/index.js, src/components/Simulation/SimulationBlock/Table/styles.js, src/components/Simulation/index.js, src/constants/types.js, src/reducers/index.js, src/reducers/ui.js
=> feat: Display currently selected cell on simulation page

package.json, src/components/Simulation/ExpandableCellContent/index.js, src/components/Simulation/ExpandableCellContent/styles.js, yarn.lock
=> feat: Add code editor for simulation cell explanation

package.json, src/App.js, src/lib/shortcuts.js, yarn.lock
Went for react-shortcuts even though react-hotkeys seemed more popular because the later is searching for new maintainers as per https://github.com/greena13/react-hotkeys/commit/9974edc258e27f635bc303df5539eceb79bc55be 
If they find some maintainers, we could switch to hotkeys instead.
=> feat: Add shortcut library

mock-server/data/sets.json
Basically, if you see something that's not camelcased, I forgot to change it in the serializer. Everything should be camel cased.
=> Fix camel casing in API

mock-server/README.md, mock-server/app.rb, mock-server/data/compound.json, mock-server/data/compounds.json
A compound, a combination of formula output from multiple sets
=> Sets Group is now Compound

src/components/Sets/SetListItem/index.js, src/components/Shared/ActionFab.js, src/components/Shared/SidebarBlock.js, src/components/Simulation/SimulationBlock/PeriodView/index.js, src/components/Simulation/SimulationBlock/Table/index.js, src/components/Simulation/SimulationBlock/index.js, src/components/Simulation/SimulationBlocks.js, src/components/Simulation/SimulationResultStatus/index.js, src/components/Simulation/index.js, src/components/Simulations/SimulationListItem/index.js, src/constants/ui.js, src/containers/SetContainer/index.js, src/containers/SetsGroupsContainer/index.js, src/containers/SimulationContainer/index.js, src/containers/SimulationsContainer/index.js, src/lib/translations/en.js, src/lib/translations/fr.js
simulation button leads to correct simulation except: 
- simulation doesn't keep the filters on when you specify the org unit
- it’ doesn't fetch the first period from the project yet.
=> feat: Fetch set from api and add fab sim btn

src/components/Compounds/Compound/index.js, src/containers/CompoundContainer/index.js, src/lib/translations/en.js, src/lib/translations/fr.js
Sets info will appear when api will have them normally
=> feat: Add sidesheet to compound modal

package.json, src/containers/SetCurrentLevelContainer/index.js, src/index.css, yarn.lock
=> feat: Add data grid for set show

src/App.js, src/components/Compounds/Compound/index.js, src/components/Sets/SetsFilters/index.js, src/components/Sets/index.js, src/components/Simulation/ExpandableCellContent/ViewOnDhis2Btn/index.js, src/components/Simulation/SimulationBlocks.js, src/containers/SetContainer/index.js, src/containers/SetsContainer/index.js, src/containers/SimulationContainer/index.js
=> feat: Add filters to sets index
